### ISSUE TITLE
Dataset availability 

### ISSUE THREAD

**Issue by zaidalyafeai** [Tariq60/arastance#1]
Any plans to publish the dataset ?

**Comment by Tariq60** [comment]
Yes, I wanted to do some cleaning of the data before releasing it but never got around to it during the summer... I'll finalize the data and release it this upcoming weekend... Sorry for the delay

**Comment by zaidalyafeai** [comment]
Awesome, looking forward !

**Comment by Tariq60** [comment]
dataset released
